"""Update TikTok account model

Revision ID: 8324dbbed130
Revises: f035fc1f1715
Create Date: 2026-07-16 23:58:00.583134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8324dbbed130'
down_revision = 'f035fc1f1715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('scope')

    # ### end Alembic commands ###
